/* Generated By:JavaCC: Do not edit this line. Parser2aplConstants.java */
package apapl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser2aplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FILENAME = 9;
  /** RegularExpression Id. */
  int INCLHEAD = 10;
  /** RegularExpression Id. */
  int BELUPDHEAD = 11;
  /** RegularExpression Id. */
  int BBHEAD = 12;
  /** RegularExpression Id. */
  int GBHEAD = 13;
  /** RegularExpression Id. */
  int PGRULEHEAD = 14;
  /** RegularExpression Id. */
  int PRRULEHEAD = 15;
  /** RegularExpression Id. */
  int PCRULEHEAD = 16;
  /** RegularExpression Id. */
  int PLANHEAD = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int TESTAND = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int THEN = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int SKIPPLAN = 28;
  /** RegularExpression Id. */
  int SEND = 29;
  /** RegularExpression Id. */
  int PRINT = 30;
  /** RegularExpression Id. */
  int CREATE = 31;
  /** RegularExpression Id. */
  int CLONE = 32;
  /** RegularExpression Id. */
  int RELEASE = 33;
  /** RegularExpression Id. */
  int EXECUTE = 34;
  /** RegularExpression Id. */
  int UPDATEBB = 35;
  /** RegularExpression Id. */
  int GOALACTION = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int SEMICOLON = 38;
  /** RegularExpression Id. */
  int CUT = 39;
  /** RegularExpression Id. */
  int B = 40;
  /** RegularExpression Id. */
  int G = 41;
  /** RegularExpression Id. */
  int GE = 42;
  /** RegularExpression Id. */
  int P = 43;
  /** RegularExpression Id. */
  int AT = 44;
  /** RegularExpression Id. */
  int SLASHJADE = 45;
  /** RegularExpression Id. */
  int UNDERSCORE = 46;
  /** RegularExpression Id. */
  int LBRACE = 47;
  /** RegularExpression Id. */
  int RBRACE = 48;
  /** RegularExpression Id. */
  int LISTL = 49;
  /** RegularExpression Id. */
  int LISTR = 50;
  /** RegularExpression Id. */
  int ACCL = 51;
  /** RegularExpression Id. */
  int ACCR = 52;
  /** RegularExpression Id. */
  int LEFTARROW = 53;
  /** RegularExpression Id. */
  int DOT = 54;
  /** RegularExpression Id. */
  int IMPL = 55;
  /** RegularExpression Id. */
  int RELATIONAL = 56;
  /** RegularExpression Id. */
  int SIGN = 57;
  /** RegularExpression Id. */
  int IDENT = 58;
  /** RegularExpression Id. */
  int VARNAME = 59;
  /** RegularExpression Id. */
  int NUM = 60;
  /** RegularExpression Id. */
  int NUMNAME = 61;
  /** RegularExpression Id. */
  int NAMEDOT = 62;
  /** RegularExpression Id. */
  int VERT = 63;
  /** RegularExpression Id. */
  int QUOTE = 64;
  /** RegularExpression Id. */
  int QUOTE1 = 65;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_INCLUDE_SECTION = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<FILENAME>",
    "\"include:\"",
    "\"beliefupdates:\"",
    "\"beliefs:\"",
    "\"goals:\"",
    "\"pgrules:\"",
    "\"prrules:\"",
    "\"pcrules:\"",
    "\"plans:\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"&&\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"skip\"",
    "\"send\"",
    "\"print\"",
    "\"create\"",
    "\"clone\"",
    "\"release\"",
    "\"execute\"",
    "\"updateBB\"",
    "<GOALACTION>",
    "\",\"",
    "\";\"",
    "\"!\"",
    "\"B\"",
    "\"G\"",
    "\"!G\"",
    "\"P\"",
    "\"@\"",
    "\"/JADE\"",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"<-\"",
    "\".\"",
    "\":-\"",
    "<RELATIONAL>",
    "<SIGN>",
    "<IDENT>",
    "<VARNAME>",
    "<NUM>",
    "<NUMNAME>",
    "<NAMEDOT>",
    "\"|\"",
    "<QUOTE>",
    "<QUOTE1>",
    "\"*\"",
    "\"/\"",
  };

}
